# Generated by Django 5.1 on 2024-08-21 08:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
    ]
