# Generated by Django 5.1 on 2024-08-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comments_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='reply',
            new_name='reply_to',
        ),
    ]
