# Generated by Django 5.1 on 2024-08-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
